database/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include('sitedb.urls')),
    path('', include('sitedb.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += [
    path('api-token-auth/', views.obtain_auth_token)
]

sitedb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('persons/', views.PersonsView.as_view(), name='persons'),
    path('victims/', views.VictimsView.as_view(), name='victims'),
    path('guilty/', views.GuiltyView.as_view(), name='guilty'),
    path('cases/', views.CasesView.as_view(), name='cases'),
    path('persons/<int:pk>', views.PersonsDetailView.as_view(), name='one_person'),
    path('cases/<int:pk>', views.CaseDetailView.as_view(), name='one_case'),
    path('acts/', views.ActsListView.as_view(), name='acts'),
    path('acts/<int:pk>', views.ActDetailView.as_view(), name='one_act'),
    path('articles/', views.ArticleListView.as_view(), name='articles'),
    path('articles/<int:pk>', views.ArticleDetailView.as_view(), name='one_article'),
    path('organisations/', views.OrgListView.as_view(), name='organisations'),
    path('organisations/<int:pk>', views.OrgDetailView.as_view(), name='one_org'),
    path('persecutions/', views.PersecutionListView.as_view(), name='persecutions'),
    path('persons_api/', views.PersonsViewAPI.as_view()),
    path('persons_api/<int:pk>', views.SinglePersonsViewAPI.as_view()),
    path('structures_api/', views.StructuresViewAPI.as_view()),
    path('structures_api/<int:pk>', views.SingleStructureViewAPI.as_view()),
    path('cases_api/', views.CasesViewAPI.as_view()),
    path('cases_api/<int:pk>', views.SingleCaseViewAPI.as_view()),
    path('organisations/api/', views.OrganisationsViewAPI.as_view()),
    path('organisations/api/<int:pk>', views.SingleOrganisationViewAPI.as_view()),
    path('pow_api/', views.PlaceOfWorkViewAPI.as_view()),
    path('pow_api/<int:pk>', views.SinglePlaceOfWorkViewAPI.as_view()),
    path('articles/api/', views.ArticleViewAPI.as_view()),
    path('articles/api/<int:pk>', views.SingleArticleViewAPI.as_view()),
    path('persecution_api/', views.PersecutionViewAPI.as_view()),
    path('persecution_api/<int:pk>', views.SinglePersecutionViewAPI.as_view()),
    path('aip_api/', views.AiPViewAPI.as_view()),
    path('aip_api/<int:pk>', views.SingleAiPViewAPI.as_view()),
    path('rights_api/', views.RightsViewAPI.as_view()),
    path('rights_api/<int:pk>', views.SingleRightsViewAPI.as_view()),
    path('status_api/', views.StatusViewAPI.as_view()),
    path('status_api/<int:pk>', views.SingleStatusViewAPI.as_view()),
    path('acts_api/', views.ActViewAPI.as_view()),
    path('acts_api/<int:pk>', views.SingleActViewAPI.as_view()),
    path('via_api/', views.ViAAPI.as_view()),
    path('via_api/<int:pk>', views.SingleViAAPI.as_view()),
    path('pia_api/', views.PersonInActAPI.as_view()),
    path('pia_api/<int:pk>', views.SinglePersonInActAPI.as_view()),
    path('depriving_api/', views.DeprivingAPI.as_view()),
    path('depriving_api/<int:pk>', views.SingleDeprivingAPI.as_view()),

    # path('persons_api/', views.PersonsViewAPI.as_view()),
    # path('persons_api/<int:pk>', views.SinglePersonsViewAPI.as_view()),
]

sitedb/models.py
from django.db import models

"""
admin
1111111
"""


class Person(models.Model):
    name = models.CharField('ФИО', max_length=250)
    date_of_birth = models.DateField('Дата рождения', blank=True, null=True)
    biography = models.TextField('биография', blank=True, null=True)
    photo = models.ImageField(upload_to='sitedb/images/person', default='images/Noface.JPG', null=True)
    citizenship = models.CharField('гражданство', max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name


class Structure(models.Model):
    name = models.CharField('короткое название', max_length=50)
    overwrite = models.TextField('описание', blank=True, null=True)
    logo = models.ImageField(upload_to='sitedb/images/structure', default='images/Nologo.JPG', null=True)
    def __str__(self):
        return self.name


class Organisation(models.Model):
    short_name = models.CharField('короткое название', max_length=250)
    full_name = models.CharField('полное название', max_length=250, blank=True, null=True)
    address = models.CharField('адрес', max_length=250, blank=True, null=True)
    phonenumber = models.CharField('телефон', max_length=20, blank=True, null=True)
    site_org = models.URLField('сайт', max_length=250, blank=True, null=True)
    Email = models.URLField('E-mail', max_length=250, blank=True, null=True)
    srtucture = models.ForeignKey(Structure, on_delete=models.CASCADE, blank=True, null=True)
    prison = models.BooleanField('место лишения свободы', default=False, blank=True, null=True)
    state = models.CharField('страна расположения', max_length=250, blank=True, null=True)
    main_org = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.short_name


class PlaceOfWork(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    оrganisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, blank=True, null=True)
    position = models.CharField('должность', max_length=250, blank=True, null=True)
    rank = models.CharField('звание', max_length=250, blank=True, null=True)
    date = models.DateField('начало работы', blank=True, null=True)
    date_of_end = models.DateField('прекращение работы', blank=True, null=True)
    notes = models.TextField('пометки', blank=True, null=True)


class Article(models.Model):
    """
    статья обвинения
    для оптимизации на этом этапе parts выглядит "222 ч.3",
    логичнее parts указать как числовое значение, но тогда нужен адаптер
    """

    codes_choices = [
        ('УК', 'Уголовный кодекс'),
        ('КоАП', 'Кодекс об административных правонарушениях')
    ]
    number = models.CharField('статья', max_length=10)
    parts = models.CharField('часть', max_length=20, blank=True, null=True)
    code = models.CharField('кодекс', max_length=10, choices=codes_choices, default='УК')
    title = models.TextField('название', blank=True, null=True)
    text = models.TextField('текст', blank=True, null=True)

    def __str__(self):
        return "ст.%s %s" % (self.parts, self.code)


class Case(models.Model):
    name = models.CharField('Дело', max_length=250)
    overview = models.TextField('описание', blank=True, null=True)
    photo = models.ImageField(upload_to='static/images/cases', default='images/Noface.JPG', blank=True, null=True)

    def __str__(self):
        return self.name


class Persecution(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE, blank=True, null=True)
    victim = models.ForeignKey(Person, on_delete=models.CASCADE)
    type_of_pers = models.CharField('Тип преследования', max_length=20, blank=True, null=True)
    date = models.DateField('Дата преследования', max_length=10, blank=True, null=True)
    overview = models.TextField('описание', blank=True, null=True)
    permission_level = models.IntegerField('допуск', default=0)

    def __str__(self):
        return "%s_%s_%s" % (self.case,self.victim,self.type_of_pers)


class ArticlesInPersecution(models.Model):
    persecution = models.ForeignKey(Persecution, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)


class H_Rights(models.Model):
    rights = models.CharField('Права свободы', max_length=150, unique=True)
    echr_article = models.CharField('статья', max_length=15, blank=True, null=True)
    content = models.TextField('описание', blank=True, null=True)

    def __str__(self):
        return self.rights


class StatusOfVictimInPers(models.Model):
    persecution = models.ForeignKey(Persecution, on_delete=models.CASCADE)
    status = models.CharField('статус', max_length=100, default='Підозрюваний')
    date = models.DateField('Дата начала статуса',max_length=10, blank=True, null=True)
    date_of_end = models.DateField('Окончание статуса',max_length=10, blank=True, null=True)

class Act(models.Model):
    """
    Акт преследования
    """
    date = models.DateField('Начало',max_length=10, blank=True, null=True)
    date_of_end = models.DateField('Окончание',max_length=10, blank=True, null=True)
    persecution = models.ForeignKey(Persecution, on_delete=models.CASCADE)
    type_of_act = models.CharField('тип акта преследования', max_length=150, blank=True, null=True)
    # Типы преследований в акте преследования (содержание под стражей, обыск и т.п.

    appeal = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    сase_num = models.CharField('номер дела в суде', max_length=100, blank=True, null=True)
    сase_decision = models.CharField('тип судебного решения', max_length=50, blank=True, null=True)
    sentence = models.CharField('тип приговора', max_length=50, blank=True, null=True)
    year_sentence = models.CharField('лет', max_length=2, blank=True, null=True)
    month_sentence = models.CharField('месяцев', max_length=2, blank=True, null=True)
    day_sentence = models.CharField('дней', max_length=4, blank=True, null=True)
    penalty_sentence = models.CharField('штраф', max_length=15, blank=True, null=True)
    work_sentence = models.CharField('принудительные работы', max_length=4, blank=True, null=True)
    text_sentence = models.TextField('текст приговора', blank=True, null=True)
    overview = models.TextField('описание', blank=True, null=True)

    def __str__(self):
        return "%s_%s_%s" % (self.date, self.persecution, self.type_of_act)


class ViolationInAct(models.Model):
    """
    Права нарушенные в акте преследования
    """
    act = models.ForeignKey(Act, on_delete=models.CASCADE)
    rights = models.ForeignKey(H_Rights, on_delete=models.CASCADE)


class PersonInAct(models.Model):
    """
    Участники в акте преследования
    """
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    act = models.ForeignKey(Act, on_delete=models.CASCADE)
    status_in_act = models.CharField('статус в акте', max_length=250, default="Винний")
    role = models.CharField('роль в акте', max_length=250, blank=True, null=True)

class OrganisationInAct(models.Model):
    """
    Участники в акте преследования
    """
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    act = models.ForeignKey(Act, on_delete=models.CASCADE)

class Depriving_Liberty(models.Model):
    """
    Лишения свободы в преследовании
    """
    persecution = models.ForeignKey(Persecution, on_delete=models.CASCADE)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    date = models.DateField('Начало', max_length=10)
    date_of_end = models.DateField('Окончание', max_length=10, blank=True, null=True)
    condition = models.CharField('Умови', max_length=250, blank=True, null=True)  # ШИЗО, ПКТ, камера, палата
    status = models.CharField('Статус', max_length=250, blank=True, null=True)  # колония, содержание под стражей, арест, медчасть
    overview = models.TextField('описание', blank=True, null=True)

# Синхронизировано
# Не создано ссылки на акт, на работу, на лишение свободы, на статус в деле, на дело, на человека. соцсети и контанкты,

sitedb/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

sitedb/templates/sitedb/act_list.html
{% extends 'sitedb/layout.html' %}

{% block title %}Персоналии{% endblock %}

{% block main %}
    <h2>Отдельные акты в преследованиях имеющихся в базе</h2>
<li><ul>Всего в базе: {{ total }}  </ul>
    <ul>Выбрано: {{ selected }} </ul></li>
    <body>
        {% include 'sitedb/pagination.html' %}

        {% block body %}
        {% for act in object_list %}
            {% include 'sitedb/act_inf.html' %}
        {% endfor %}
        {% endblock %}

        {% include 'sitedb/pagination.html' %}
    </body>

{% endblock%}

{% block search %}
    <form id="search-form" action=''  method="GET">
        <input name="q_pers" id="search-field" type="text" placeholder="Search..." onkeyup="input_Func(event)">
    </form>
{% endblock %}

{% block filtres %}
<h2>Фильтры</h2>
    <form id="filter-form" action='/acts/'  method="GET">
        {% include 'sitedb/filtres_restiction.html' %}
        <br>
        <input type="submit" value="Select/Reset">
    </form>
{% endblock %}

{% block navigation %}
{% endblock %}

sitedb/templates/sitedb/article_detail.html
{% extends 'sitedb/layout.html' %}

{% block main %}
<div class = 'article_inf'>

    <h2> Статья: {{ article }}</h2>
    <li> {{ article.title }}</li>
    <br>

    <h3>Преследования по этой статье</h3>
    {% for persc in persecutions %}
        {% include 'sitedb/persecution_information.html' %}
    {% endfor %}

{% endblock %}

sitedb/templates/sitedb/guilty.html
{% extends 'sitedb/persons.html' %}

{% block title %}Виновные{% endblock %}

{% block body_head %}
<h1> Список виновных </h1>
<h2> Всего в базе: {{ total }}. Выбрано: {{ selected }}. </h2>
{% endblock %}

{% block filtres %}
<h2>Фильтры</h2>
    <form id="filter-form" action='/guilty/'  method="GET">
        {% include 'sitedb/filtres_restiction.html' %}
        <br>
        <input type="submit" value="Select/Reset">
    </form>
{% endblock %}

sitedb/templates/sitedb/index.html
{% extends 'sitedb/layout.html' %}

{% block title %}Главная{% endblock %}

{% block main %}

<div class="greeting">
    {% if user.is_authenticated %}
    <h2>Приветствуем {{ user.get_username }} в базе нарушений прав человека в Крыму</h2>
    {% else %}
    <h2>Приветствуем в базе нарушений прав человека в Крыму</h2>
    {% endif %}
    <p>База данных Крымской правозащитной группы содержит информацию о {{ persecution | length}} преследованиях,
        в отношении {{ victims | length}} человек. В рамках этих преследований зафиксировано  {{ acts | length}} отдельных актов
        нарушающих права человека.
<!--        В том числе:-->
<!--        {% for key, value in violations.items %}-->
<!--            <ul> {{ key }}: <b>{{ value|length }}</b></ul>-->
<!--        {% endfor %}-->

    </p>

    <p>Сегодня в местах лишения свободы находятся {{ prisoners | length}} человек.
    </p>

</div>
<div style="width:  900px; height: 500px"><canvas id="chartDepr"></canvas></div>
<div style="width:  900px; height: 500px"><canvas id="chartCriminal"></canvas></div>
<div style="width:  900px; height: 500px"><canvas id="chartDetention"></canvas></div>


<!--<div id="curve_chart" style="width:  900px; height: 500px">-->

<!--<div id="curve_chart_adm" style="width: 900px; height: 500px"></div>-->



<!--<div id="curve_chart_depr" style="width: 900px; height: 500px"></div>-->

<!--<div class="features">-->
<!--    <h1>Главная</h1>-->
<!--    <p>Вы посещали эте страницу {{ num_visits }} раз .</p>-->
<!--    {% for val in values %}-->

<!--    <p>{{ val }}</p>-->
<!--    {% endfor %}-->
<!--</div>-->

{% endblock%}

sitedb/templates/sitedb/org_detail.html
{% extends 'sitedb/layout.html' %}

{% block title %}
{{ head }}
{% endblock %}

{% block main %}
<h2>{{ head }}</h2>
<br>
{% if object.full_name %}
<li>Название организации: {{ object.full_name }}</li>
{% endif %}
{% if object.address %}
<li>Адрес: {{ object.address }}</li>
{% endif %}
{% if object.phonenumber %}
<li>Телефон: {{ object.phonenumber }}</li>
{% endif %}
{% if object.site_org %}
<li>Сайт: {{ object.site_org }}</li>
{% endif %}
{% if object.Email %}
<li>Электронный адрес: {{ object.Email }}</li>
{% endif %}
{% if object.srtucture %}
<li>Структурное подразделение: {{ object.srtucture }}</li>
{% endif %}
<br>
{% if staff %}
<h3>Сотрудники организации:</h3>
    {% for pow in staff %}
    <li><a href="{% url 'one_person' pow.person.id %}">{{ pow.person }}</a>
         Должность {{ pow.position }}
        {% if pow.date %}
             С {{ pow.date }}
                {% if pow.date_of_end %}
             по {{ pow.date_of_end }}
            {% endif %}
        {% endif %}
    </li>
    {% endfor %}
{% endif %}
<br>
{% if prisoner %}
<h3>Лица, которые здесь содержатся: </h3>
<br>
{% for item in prisoner %}
    {% with pers=item.persecution.victim %}
    {% include 'sitedb/person_information.html' %}
    {% endwith %}
{% endfor %}
{% endif %}

{% endblock %}

sitedb/templates/sitedb/org_inf.html
<div class = "organisation_inf">
    {% if  org.srtucture.logo  %}
        <img src={{ org.srtucture.logo.url  }}  height="60" >
    {% endif %}
    <h3><a href="{% url 'one_org' org.id %}">{{ org }}</a></h3>
    {% if  org.deprivings  %}
    <p>Сейчас в {{ org }} содержится <b>{{ org.deprivings }}</b>
        {% if  org.deprivings ==  1 %}
            крымский политзаключенный
        {% else %}
            крымских политзаключенных
        {% endif %}
        </p>
    {% endif %}
</div>

sitedb/templates/sitedb/pagination.html
{% include 'sitedb/pagin.html' %}

sitedb/templates/sitedb/persecution_information.html
<div class = 'persecution'>
    {% if persc.act_set.all %}

    {% if object.type != "Person" %}
         {% if persc.victim.photo %}
        <img src={{ persc.victim.photo.url }}  height="80" >
        {% endif %}
    {% endif %}
    <div class ='persecution_inf'>
        <h3><a href="{% url 'one_person' persc.victim.id %}"><b>{{ persc.victim.name }}</b></a></h3>
        <li>Кейс: <a href="{% url 'one_case' persc.case.id %}">{{ persc.case }}</a></li>
        <li>Начало преследования: {{ persc.date }}</li>
        <li>Тип преследования:
            {% if persc.type_of_pers == 'УК' %}
                Уголовное
            {% else  %}
                {{ persc.type_of_pers }}
            {% endif %}
            </li>
        <li>Статьи обвинения:
            {% for art_in_pers in persc.articlesinpersecution_set.all %}
                <a href="{% url 'one_article' art_in_pers.article.id %}">{{ art_in_pers.article }}</a>,
            {% endfor %}
        </li>

        {% if persc.status %}
        <li>Статус в деле: {{ persc.status.status }}</li>
        {% endif %}

        {% if persc.sentence %}
            <li>
            {% if persc.type_of_pers == 'УК' %}
                Вынесен приговор: <b>{{ persc.sentence_text }}</b>
             {% else  %}
                Административное наказание: <b>{{ persc.sentence_text }}</b>
            {% endif %}

            </li>
        {% endif %}

        <div class="btn-group">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              Акты в преследовании:
          </button>
          <div class="dropdown-menu">
            {% if persc.acts %}
            {% for act in  persc.acts %}
                <li><a href="{% url 'one_act' act.id %}">{{ act.date }} - {{ act.type_of_act }}
                    {% if  act.сase_decision %}
                        - {{ act.сase_decision }}
                    {% endif %}
                </a></li>
             {% endfor %}
             {% else %}
            {% for act in persc.act_set.all %}
                <li><a href="{% url 'one_act' act.id %}">{{ act.date }} - {{ act.type_of_act }}
                    {% if  act.сase_decision %}
                        - {{ act.сase_decision }}
                    {% endif %}
                </a></li>
             {% endfor %}
            {% endif %}

          </div>
        </div>

        {% if user.is_authenticated %}

        <div class="btn-group">
            {% if persc.guilty %}
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          {% else %}
             <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"
          onclick="take_items_list('{{ persc.id }}')">
          {% endif %}
            Причастные к преследованию:
          </button>
          <div class="dropdown-menu" id="{{ persc.id }}" data="{% url 'persons' %}">
            <ul class="item_list">
                {% for person in persc.guilty %}
                    <li><a href="{% url 'one_person' person.id %}">{{ person.name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}
    </div>
    {% endif %}
</div>

sitedb/templates/sitedb/persecution_list.html
{% extends 'sitedb/layout.html' %}

{% block title %}
{% endblock %}

{% block main %}
    <h2>Преследования в базе</h2>
<li><ul>Всего : {{ total }}  </ul>
    <ul>Выбрано: {{ selected }} </ul></li>
    <body>
    {% include 'sitedb/pagination.html' %}
        {% block body %}
        {% for persc in object_list %}
        {% include 'sitedb/persecution_information.html' %}
        {% endfor %}
        {% endblock %}
    {% include 'sitedb/pagination.html' %}
    </body>

{% endblock%}

{% block nav %}
    <form id="search-form_nav" action=''  method="GET">
        <div class="btn-group dropdown">
            <button class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
             Choise
            </button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"  id="choise">
                <ul>
                    <input type="text" class="{{ key }}" placeholder="choice..." id="myInput" onkeyup="fil_Func('choise')">
                    {% for obj in rest %}
                        <a href="{% url 'one_person' obj.victim.id %}"><li>{{ obj.victim.name }}</li></a>
                    {% endfor %}
                </ul>
            </div>

    </div>
            </form>
    <form id="search" action=''  method="GET">
            <input name="q_pers" id="search-field_nav" type="text" placeholder="Search..." onkeyup="input_Func(event)">
    </form>
{% endblock %}

{% block filtres %}
<h2>Фильтры</h2>
    <form id="filter-form" action='/persecutions/'  method="GET">
        {% include 'sitedb/filtres_restiction.html' %}
        <br>
        <input type="submit" value="Select/Reset">
    </form>
{% endblock %}

{% block navigation %}
{% endblock %}

sitedb/templates/sitedb/person_information.html
<div class="person_box">
<a href="{% url 'one_person' pers.id %}"><div class="person">
     <center><b>{{ pers.name }}</b> </center>
    {% if  pers.photo  %}
        <img src={{ pers.photo.url }}  height="80" >
    {% endif %}
</div></a>
</div>

sitedb/templates/sitedb/persons.html
{% extends 'sitedb/layout.html' %}

{% block title %}Субъекты{% endblock %}

{% block main %}
    {% block body_head %}{% endblock %}
    <body>
        {% include 'sitedb/pagination.html' %}
        <div class="persons_list">
        {% block body %}
        {% for pers in object_list %}
            {% include 'sitedb/person_information.html' %}
        {% endfor %}
        {% endblock %}
        </div>
        {% include 'sitedb/pagination.html' %}
    </body>

{% endblock%}

{% block search %}
    <a href="{% url 'victims' %}"> <li><i class="fas fa-child"></i> Пострадавшие</li></a>
    {% if user.is_authenticated %}
        <a href="{% url 'guilty' %}"> <li><i class="fas fa-child"></i> Виновные</li></a>
    {% endif %}
{% endblock %}

{% block nav %}
    <form id="search-form_nav" action=''  method="GET">
        <div class="btn-group dropdown">
            <button class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
             Choise
            </button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"  id="choise">
                <ul>
                    <input type="text" class="{{ key }}" placeholder="choice..." id="myInput" onkeyup="fil_Func('choise')">
                    {% for obj in rest %}
                        <a href="{% url 'one_person' obj.id %}"><li>{{ obj.name }}</li></a>
                    {% endfor %}
                </ul>
            </div>

    </div>
            </form>
    <form id="search" action=''  method="GET">
            <input name="q" id="search-field_nav" type="text" placeholder="Search..." onkeyup="input_Func(event)">
    </form>
{% endblock %}

sitedb/templates/sitedb/register.html
{% extends 'sitedb/layout.html' %}

{% block title %}Create an account{% endblock %}

{% block main %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

sitedb/templates/sitedb/temporaly.html
<div class="person">
    <img src={{ pers.photo.url }}  height="80" >
    <div class="person_data">
            <h3><a href="{% url 'person' pers.id %}">{{ pers.name }}</a></h3>
            {% if  pers.date_of_birth != None %}
                <li>Дата рождения {{ pers.date_of_birth }}</li>
            {% endif %}
            {% if  pers.citizenship != None %}
                <li>Гражданство: {{ pers.citizenship }}</li>
            {% endif %}

    </div>
</div>

sitedb/templates/sitedb/victims.html
{% extends 'sitedb/persons.html' %}

{% block title %}Пострадавшие{% endblock %}

{% block body_head %}
<h1> Список пострадавших </h1>
<h2> Всего в базе: {{ total }}. Выбрано: {{ selected }}. </h2>
{% endblock %}

{% block filtres %}
<h2>Фильтры</h2>
    <form id="filter-form" action='/victims/'  method="GET">
        <div class="custom-control custom-switch">
            {% if rest_form %}
            <input type="checkbox" class="custom-control-input" id="customSwitch1" name="allpers" checked>
            <label class="custom-control-label" for="customSwitch1">Показать всех</label>
            {% else %}
            <input type="checkbox" class="custom-control-input" id="customSwitch1" name="allpers" >
            <label class="custom-control-label" for="customSwitch1">Показать лишенных свободы</label>
            {% endif %}
        </div>
        <br>
        {% include 'sitedb/filtres_restiction.html' %}
        <br>
        <input type="submit" value="Select / Reset">
    </form>
{% endblock %}